name: libusb
description: Dart wrapper via `dart:ffi` for https://github.com/libusb/libusb
version: 0.4.23-dev.1+1
homepage: https://github.com/woodemi/libusb.dart

environment:
  sdk: ^3.0.1

platforms:
  linux:
  macos:
  windows:

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  ffigen: ^9.0.1
  test: ^1.21.0
  convert: ^3.0.0